# Generated by Django 5.0.14 on 2026-03-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('leader', 'Leader'), ('government', 'Government'), ('admin', 'Admin')], default='citizen', max_length=12),
        ),
    ]
