# Generated by Django 5.0.14 on 2026-03-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0003_change_language_default_to_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firebase_uid",
            field=models.CharField(
                blank=True,
                help_text="Firebase Authentication UID",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_anonymous_user",
            field=models.BooleanField(
                default=False, help_text="True if created via Firebase Anonymous Auth"
            ),
        ),
    ]
