# Generated by Django 5.0.14 on 2026-02-26 16:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import pgvector.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo_intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GramSabhaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('transcript', models.TextField(blank=True)),
                ('summary_s3_key', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gram_sabha_sessions', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gram_sabha_sessions', to='geo_intelligence.village')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('water', 'Water Access'), ('road', 'Road'), ('health', 'Health'), ('education', 'Education'), ('electricity', 'Electricity'), ('sanitation', 'Sanitation'), ('other', 'Other')], max_length=20)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('description_text', models.TextField()),
                ('description_hindi', models.TextField(blank=True)),
                ('audio_s3_key', models.CharField(blank=True, max_length=500)),
                ('photo_s3_key', models.CharField(blank=True, max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('ward', models.IntegerField(blank=True, null=True)),
                ('urgency', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('adopted', 'Adopted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='reported', max_length=20)),
                ('vote_count', models.IntegerField(default=0)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1024, null=True)),
                ('is_gram_sabha', models.BooleanField(default=False)),
                ('transcribe_job_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='geo_intelligence.village')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GramSabhaIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vote_count', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='community.gramsabhasession')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gram_sabha_issues', to='community.report')),
            ],
            options={
                'ordering': ['-vote_count'],
            },
        ),
        migrations.CreateModel(
            name='ReportCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('water', 'Water Access'), ('road', 'Road'), ('health', 'Health'), ('education', 'Education'), ('electricity', 'Electricity'), ('sanitation', 'Sanitation'), ('other', 'Other')], max_length=20)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('radius_km', models.FloatField()),
                ('report_count', models.IntegerField(default=0)),
                ('ward_count', models.IntegerField(default=0)),
                ('upvote_count', models.IntegerField(default=0)),
                ('estimated_households', models.IntegerField(blank=True, null=True)),
                ('community_priority_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='geo_intelligence.village')),
            ],
            options={
                'ordering': ['-community_priority_score'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='community.reportcluster'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.report')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('report', 'voter')},
            },
        ),
    ]
