# Generated by Django 5.0.14 on 2026-02-26 16:21

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('ministry', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pdf_s3_key', models.CharField(blank=True, max_length=500)),
                ('max_subsidy_pct', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FundConvergencePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost_inr', models.BigIntegerField()),
                ('panchayat_contribution_inr', models.BigIntegerField()),
                ('savings_pct', models.FloatField()),
                ('schemes_used', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_convergence_plans', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.TextField()),
                ('rule_type', models.CharField(max_length=50)),
                ('embedding', pgvector.django.VectorField(dimensions=1024)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='scheme_rag.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('section_header', models.CharField(blank=True, max_length=200)),
                ('chunk_type', models.CharField(choices=[('eligibility', 'Eligibility'), ('fund_allocation', 'Fund Allocation'), ('documents', 'Documents Required'), ('process', 'Application Process'), ('general', 'General')], default='general', max_length=50)),
                ('embedding', pgvector.django.VectorField(dimensions=1024)),
                ('token_count', models.IntegerField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='scheme_rag.scheme')),
            ],
            options={
                'ordering': ['scheme', 'chunk_index'],
            },
        ),
    ]
