# Generated by Django 5.0.14 on 2026-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('transcribe', 'Voice Transcription'), ('categorize', 'Report Categorization'), ('cluster', 'Report Clustering'), ('score', 'Priority Scoring'), ('recommend', 'Project Recommendation'), ('rag_query', 'Scheme RAG Query')], max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriorityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_score', models.FloatField()),
                ('data_score', models.FloatField()),
                ('urgency_score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('score_breakdown', models.JSONField(blank=True, null=True)),
                ('report_count_pts', models.FloatField()),
                ('geographic_spread_pts', models.FloatField()),
                ('upvote_pts', models.FloatField()),
                ('gram_sabha_bonus', models.FloatField()),
                ('satellite_pts', models.FloatField()),
                ('data_gap_pts', models.FloatField()),
                ('demographic_pts', models.FloatField()),
                ('economic_pts', models.FloatField()),
                ('seasonal_pts', models.FloatField()),
                ('safety_pts', models.FloatField()),
                ('worsening_trend_pts', models.FloatField()),
                ('justification', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-total_score'],
            },
        ),
    ]
