# Generated by Django 5.0.14 on 2026-02-26 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorityscore',
            name='cluster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority_score', to='community.reportcluster'),
        ),
    ]
