# Generated by Django 5.0.14 on 2026-02-26 16:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lgd_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lgd_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lgd_code', models.CharField(max_length=10, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='geo_intelligence.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Panchayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lgd_code', models.CharField(max_length=10, unique=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('households', models.IntegerField(blank=True, null=True)),
                ('area_sq_km', models.FloatField(blank=True, null=True)),
                ('fund_available_inr', models.BigIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panchayats', to='geo_intelligence.block')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='geo_intelligence.state'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lgd_code', models.CharField(max_length=10, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('households', models.IntegerField(blank=True, null=True)),
                ('agricultural_households', models.IntegerField(blank=True, null=True)),
                ('groundwater_depth_m', models.FloatField(blank=True, null=True)),
                ('ndvi_score', models.FloatField(blank=True, null=True)),
                ('ndvi_updated_at', models.DateTimeField(blank=True, null=True)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='geo_intelligence.panchayat')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infra_type', models.CharField(choices=[('school', 'School'), ('hospital', 'Hospital'), ('market', 'Market'), ('water_source', 'Water Source'), ('road', 'Road')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=50)),
                ('distance_from_center_km', models.FloatField(blank=True, null=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='geo_intelligence.village')),
            ],
            options={
                'verbose_name_plural': 'Infrastructure',
            },
        ),
    ]
