# Generated by Django 5.0.14 on 2026-03-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayat',
            name='ward_count',
            field=models.IntegerField(default=9),
        ),
    ]
