# Generated by Django 5.0.14 on 2026-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('agmarknet', 'Agmarknet Prices'), ('egram_swaraj', 'eGramSwaraj'), ('bhuvan_ndvi', 'Bhuvan NDVI'), ('cgwb', 'CGWB Groundwater'), ('disha', 'DISHA Dashboard'), ('census', 'Census Data'), ('osm', 'OpenStreetMap')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('commodity', models.CharField(max_length=100)),
                ('mandi', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('price_min', models.FloatField(blank=True, null=True)),
                ('price_max', models.FloatField(blank=True, null=True)),
                ('price_modal', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'commodity', 'mandi')},
            },
        ),
    ]
