# Generated by Django 5.0.14 on 2026-03-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasynclog',
            name='source',
            field=models.CharField(choices=[('agmarknet', 'Agmarknet Prices'), ('egram_swaraj', 'eGramSwaraj'), ('bhuvan_ndvi', 'Bhuvan NDVI'), ('cgwb', 'CGWB Groundwater'), ('disha', 'DISHA Dashboard'), ('census', 'Census Data'), ('osm', 'OpenStreetMap'), ('myscheme', 'myScheme.gov.in'), ('datagov', 'data.gov.in')], max_length=20),
        ),
        migrations.CreateModel(
            name='DistrictSchemeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_lgd', models.CharField(db_index=True, max_length=10)),
                ('district_name', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('scheme', models.CharField(choices=[('mgnrega', 'MGNREGA'), ('jjm', 'Jal Jeevan Mission'), ('pmay_g', 'PMAY-G'), ('sbm_g', 'SBM-G'), ('pm_kisan', 'PM-KISAN'), ('pmgsy', 'PMGSY'), ('pm_kusum', 'PM-KUSUM')], max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('person_days_generated', models.BigIntegerField(blank=True, null=True)),
                ('households_employed', models.IntegerField(blank=True, null=True)),
                ('expenditure_inr', models.BigIntegerField(blank=True, null=True)),
                ('works_completed', models.IntegerField(blank=True, null=True)),
                ('tap_connections_target', models.IntegerField(blank=True, null=True)),
                ('tap_connections_achieved', models.IntegerField(blank=True, null=True)),
                ('coverage_pct', models.FloatField(blank=True, null=True)),
                ('beneficiary_count', models.IntegerField(blank=True, null=True)),
                ('amount_released_inr', models.BigIntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'District Scheme Stat',
                'verbose_name_plural': 'District Scheme Stats',
                'ordering': ['-fetched_at'],
                'unique_together': {('district_lgd', 'scheme', 'year')},
            },
        ),
    ]
