// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLis4ComqUvwKrF23GCtaDgcPbsvU7bHw',
    appId: '1:346517234015:web:1bede7594ec8fe234996ea',
    messagingSenderId: '346517234015',
    projectId: 'praja-shakti',
    authDomain: 'praja-shakti.firebaseapp.com',
    storageBucket: 'praja-shakti.firebasestorage.app',
    measurementId: 'G-G52YXN25KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV87QwIq6jeaUl7FLanuvziFHhWSTRADQ',
    appId: '1:346517234015:android:fa33ab5abb0903df4996ea',
    messagingSenderId: '346517234015',
    projectId: 'praja-shakti',
    storageBucket: 'praja-shakti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMjJTn1T-YR_OCYIO62mEPI046yr9YoVs',
    appId: '1:346517234015:ios:05845fd7cebae9b84996ea',
    messagingSenderId: '346517234015',
    projectId: 'praja-shakti',
    storageBucket: 'praja-shakti.firebasestorage.app',
    iosBundleId: 'com.example.prajashakti',
  );
}
